[package]
name = "algokit_transact"
version = "0.1.0"
edition = "2024"

[features]
test_utils = [
  "dep:ed25519-dalek",
  "dep:convert_case",
  "dep:algokit_test_artifacts",
]

[dependencies]
base32 = { workspace = true }
base64 = "0.22.1"
convert_case = { version = "0.8.0", optional = true }
derive_builder = { version = "0.20.2" }
ed25519-dalek = { version = "2.1.1", optional = true }
rmp = "0.8.12"
rmp-serde = { workspace = true }
rmpv = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde_with = { workspace = true }
sha2 = { workspace = true }
snafu = "0.8"
algokit_test_artifacts = { path = "../algokit_test_artifacts", optional = true }

[dev-dependencies]
pretty_assertions = "1.4.1"
algokit_transact = { path = '.', features = ["test_utils"] }
