/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_with::{Bytes, serde_as};

/// AccountParticipation describes the parameters used by this account in consensus protocol.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountParticipation {
    /// Selection public key (if any) currently registered for this round.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "selection-participation-key")]
    pub selection_participation_key: Vec<u8>,
    /// First round for which this participation is valid.
    #[serde(rename = "vote-first-valid")]
    pub vote_first_valid: u64,
    /// Number of subkeys in each batch of participation keys.
    #[serde(rename = "vote-key-dilution")]
    pub vote_key_dilution: u64,
    /// Last round for which this participation is valid.
    #[serde(rename = "vote-last-valid")]
    pub vote_last_valid: u64,
    /// root participation public key (if any) currently registered for this round.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "vote-participation-key")]
    pub vote_participation_key: Vec<u8>,
    /// Root of the state proof key (if any)
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "state-proof-key", skip_serializing_if = "Option::is_none")]
    pub state_proof_key: Option<Vec<u8>>,
}

impl AccountParticipation {
    /// Constructor for AccountParticipation
    pub fn new(
        selection_participation_key: Vec<u8>,
        vote_first_valid: u64,
        vote_key_dilution: u64,
        vote_last_valid: u64,
        vote_participation_key: Vec<u8>,
    ) -> AccountParticipation {
        AccountParticipation {
            selection_participation_key,
            vote_first_valid,
            vote_key_dilution,
            vote_last_valid,
            vote_participation_key,
            state_proof_key: None,
        }
    }
}
