/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::ApplicationStateSchema;
use crate::models::TealKeyValueStore;

/// Stores local state associated with an application.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationLocalState {
    /// The application which this local state is for.
    #[serde(rename = "id")]
    pub id: u64,
    /// Whether or not the application local state is currently deleted from its account.
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// Round when the account opted into the application.
    #[serde(rename = "opted-in-at-round", skip_serializing_if = "Option::is_none")]
    pub opted_in_at_round: Option<u64>,
    /// Round when account closed out of the application.
    #[serde(
        rename = "closed-out-at-round",
        skip_serializing_if = "Option::is_none"
    )]
    pub closed_out_at_round: Option<u64>,
    #[serde(rename = "schema")]
    pub schema: ApplicationStateSchema,
    #[serde(rename = "key-value", skip_serializing_if = "Option::is_none")]
    pub key_value: Option<TealKeyValueStore>,
}

impl ApplicationLocalState {
    /// Constructor for ApplicationLocalState
    pub fn new(id: u64, schema: ApplicationStateSchema) -> ApplicationLocalState {
        ApplicationLocalState {
            id,
            schema,
            deleted: None,
            opted_in_at_round: None,
            closed_out_at_round: None,
            key_value: None,
        }
    }
}
