/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::UnknownJsonValue;

/// A health check response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthCheck {
    /// Current version.
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<UnknownJsonValue>,
    #[serde(rename = "round")]
    pub round: u64,
    #[serde(rename = "is-migrating")]
    pub is_migrating: bool,
    #[serde(rename = "db-available")]
    pub db_available: bool,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<String>>,
}

impl HealthCheck {
    /// Constructor for HealthCheck
    pub fn new(
        version: String,
        round: u64,
        is_migrating: bool,
        db_available: bool,
        message: String,
    ) -> HealthCheck {
        HealthCheck {
            version,
            round,
            is_migrating,
            db_available,
            message,
            data: None,
            errors: None,
        }
    }
}
