/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LocalsRef names a local state by referring to an Address and App it belongs to.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalsRef {
    /// [d] Address in access list, or the sender of the transaction.
    #[serde(rename = "address")]
    pub address: String,
    /// [p] Application ID for app in access list, or zero if referring to the called application.
    #[serde(rename = "app")]
    pub app: u64,
}

impl LocalsRef {
    /// Constructor for LocalsRef
    pub fn new(address: String, app: u64) -> LocalsRef {
        LocalsRef { address, app }
    }
}
