/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::Transaction;

/// (empty)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LookupAssetTransactions {
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: u64,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
    #[serde(rename = "transactions")]
    pub transactions: Vec<Transaction>,
}

impl LookupAssetTransactions {
    /// Constructor for LookupAssetTransactions
    pub fn new(current_round: u64, transactions: Vec<Transaction>) -> LookupAssetTransactions {
        LookupAssetTransactions {
            current_round,
            transactions,
            next_token: None,
        }
    }
}
