/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::ApplicationLocalState;

/// (empty)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LookupAccountAppLocalStates {
    #[serde(rename = "apps-local-states")]
    pub apps_local_states: Vec<ApplicationLocalState>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: u64,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl LookupAccountAppLocalStates {
    /// Constructor for LookupAccountAppLocalStates
    pub fn new(
        apps_local_states: Vec<ApplicationLocalState>,
        current_round: u64,
    ) -> LookupAccountAppLocalStates {
        LookupAccountAppLocalStates {
            apps_local_states,
            current_round,
            next_token: None,
        }
    }
}
