/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::parameter_enums::*;
use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::AccountAssetInformationError as RustAccountAssetInformationError;

// Import all custom types used by this endpoint
use crate::models::{AccountAssetInformation, ErrorResponse};

// Import request body type if needed

/// struct for typed errors of method [`account_asset_information`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum AccountAssetInformationError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustAccountAssetInformationError> for AccountAssetInformationError {
    fn from(e: RustAccountAssetInformationError) -> Self {
        match e {
            RustAccountAssetInformationError::Status400(ErrorResponse) => {
                AccountAssetInformationError::Status400(ErrorResponse)
            }
            RustAccountAssetInformationError::Status401(ErrorResponse) => {
                AccountAssetInformationError::Status401(ErrorResponse)
            }
            RustAccountAssetInformationError::Status500(ErrorResponse) => {
                AccountAssetInformationError::Status500(ErrorResponse)
            }
            RustAccountAssetInformationError::Statusdefault() => {
                AccountAssetInformationError::Statusdefault()
            }
            RustAccountAssetInformationError::DefaultResponse() => {
                AccountAssetInformationError::DefaultResponse()
            }
            RustAccountAssetInformationError::UnknownValue(value) => {
                AccountAssetInformationError::UnknownValue(value.to_string())
            }
        }
    }
}
