/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::AccountAssetsInformationError as RustAccountAssetsInformationError;

// Import all custom types used by this endpoint
use crate::models::{AccountAssetsInformation, ErrorResponse};

// Import request body type if needed

/// struct for typed errors of method [`account_assets_information`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum AccountAssetsInformationError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustAccountAssetsInformationError> for AccountAssetsInformationError {
    fn from(e: RustAccountAssetsInformationError) -> Self {
        match e {
            RustAccountAssetsInformationError::Status400(ErrorResponse) => {
                AccountAssetsInformationError::Status400(ErrorResponse)
            }
            RustAccountAssetsInformationError::Status401(ErrorResponse) => {
                AccountAssetsInformationError::Status401(ErrorResponse)
            }
            RustAccountAssetsInformationError::Status500(ErrorResponse) => {
                AccountAssetsInformationError::Status500(ErrorResponse)
            }
            RustAccountAssetsInformationError::Statusdefault() => {
                AccountAssetsInformationError::Statusdefault()
            }
            RustAccountAssetsInformationError::DefaultResponse() => {
                AccountAssetsInformationError::DefaultResponse()
            }
            RustAccountAssetsInformationError::UnknownValue(value) => {
                AccountAssetsInformationError::UnknownValue(value.to_string())
            }
        }
    }
}
