/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::DeleteParticipationKeyByIdError as RustDeleteParticipationKeyByIdError;

// Import all custom types used by this endpoint
use crate::models::ErrorResponse;

// Import request body type if needed

/// struct for typed errors of method [`delete_participation_key_by_id`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum DeleteParticipationKeyByIdError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status404(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustDeleteParticipationKeyByIdError> for DeleteParticipationKeyByIdError {
    fn from(e: RustDeleteParticipationKeyByIdError) -> Self {
        match e {
            RustDeleteParticipationKeyByIdError::Status400(v) => {
                DeleteParticipationKeyByIdError::Status400(v.into())
            }
            RustDeleteParticipationKeyByIdError::Status401(v) => {
                DeleteParticipationKeyByIdError::Status401(v.into())
            }
            RustDeleteParticipationKeyByIdError::Status404(v) => {
                DeleteParticipationKeyByIdError::Status404(v.into())
            }
            RustDeleteParticipationKeyByIdError::Status500(v) => {
                DeleteParticipationKeyByIdError::Status500(v.into())
            }
            RustDeleteParticipationKeyByIdError::Statusdefault() => {
                DeleteParticipationKeyByIdError::Statusdefault()
            }
            RustDeleteParticipationKeyByIdError::DefaultResponse() => {
                DeleteParticipationKeyByIdError::DefaultResponse()
            }
            RustDeleteParticipationKeyByIdError::UnknownValue(v) => {
                DeleteParticipationKeyByIdError::UnknownValue(v.into())
            }
        }
    }
}
