/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::ExperimentalCheckError as RustExperimentalCheckError;

// Import all custom types used by this endpoint

// Import request body type if needed

/// struct for typed errors of method [`experimental_check`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum ExperimentalCheckError {
    Status404(),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustExperimentalCheckError> for ExperimentalCheckError {
    fn from(e: RustExperimentalCheckError) -> Self {
        match e {
            RustExperimentalCheckError::Status404() => ExperimentalCheckError::Status404(),
            RustExperimentalCheckError::Statusdefault() => ExperimentalCheckError::Statusdefault(),
            RustExperimentalCheckError::DefaultResponse() => {
                ExperimentalCheckError::DefaultResponse()
            }
            RustExperimentalCheckError::UnknownValue(v) => {
                ExperimentalCheckError::UnknownValue(v.into())
            }
        }
    }
}
