/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GenerateParticipationKeysError as RustGenerateParticipationKeysError;

// Import all custom types used by this endpoint
use crate::models::ErrorResponse;

// Import request body type if needed

/// struct for typed errors of method [`generate_participation_keys`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GenerateParticipationKeysError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Status503(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<GenerateParticipationKeysError> for RustGenerateParticipationKeysError {
    fn from(e: GenerateParticipationKeysError) -> Self {
        match e {
            GenerateParticipationKeysError::Status400(ErrorResponse) => {
                RustGenerateParticipationKeysError::Status400(ErrorResponse)
            }
            GenerateParticipationKeysError::Status401(ErrorResponse) => {
                RustGenerateParticipationKeysError::Status401(ErrorResponse)
            }
            GenerateParticipationKeysError::Status500(ErrorResponse) => {
                RustGenerateParticipationKeysError::Status500(ErrorResponse)
            }
            GenerateParticipationKeysError::Status503(ErrorResponse) => {
                RustGenerateParticipationKeysError::Status503(ErrorResponse)
            }
            GenerateParticipationKeysError::Statusdefault() => {
                RustGenerateParticipationKeysError::Statusdefault()
            }
            GenerateParticipationKeysError::DefaultResponse() => {
                RustGenerateParticipationKeysError::DefaultResponse()
            }
            GenerateParticipationKeysError::UnknownValue(value) => {
                RustGenerateParticipationKeysError::UnknownValue(value.into())
            }
        }
    }
}

impl From<RustGenerateParticipationKeysError> for GenerateParticipationKeysError {
    fn from(e: RustGenerateParticipationKeysError) -> Self {
        match e {
            RustGenerateParticipationKeysError::Status400(ErrorResponse) => {
                GenerateParticipationKeysError::Status400(ErrorResponse)
            }
            RustGenerateParticipationKeysError::Status401(ErrorResponse) => {
                GenerateParticipationKeysError::Status401(ErrorResponse)
            }
            RustGenerateParticipationKeysError::Status500(ErrorResponse) => {
                GenerateParticipationKeysError::Status500(ErrorResponse)
            }
            RustGenerateParticipationKeysError::Status503(ErrorResponse) => {
                GenerateParticipationKeysError::Status503(ErrorResponse)
            }
            RustGenerateParticipationKeysError::Statusdefault() => {
                GenerateParticipationKeysError::Statusdefault()
            }
            RustGenerateParticipationKeysError::DefaultResponse() => {
                GenerateParticipationKeysError::DefaultResponse()
            }
            RustGenerateParticipationKeysError::UnknownValue(value) => {
                GenerateParticipationKeysError::UnknownValue(value.to_string())
            }
        }
    }
}
