/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::parameter_enums::*;
use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetTransactionProofError as RustGetTransactionProofError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, TransactionProof};

// Import request body type if needed

/// struct for typed errors of method [`get_transaction_proof`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetTransactionProofError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status404(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetTransactionProofError> for GetTransactionProofError {
    fn from(e: RustGetTransactionProofError) -> Self {
        match e {
            RustGetTransactionProofError::Status400(ErrorResponse) => {
                GetTransactionProofError::Status400(ErrorResponse)
            }
            RustGetTransactionProofError::Status401(ErrorResponse) => {
                GetTransactionProofError::Status401(ErrorResponse)
            }
            RustGetTransactionProofError::Status404(ErrorResponse) => {
                GetTransactionProofError::Status404(ErrorResponse)
            }
            RustGetTransactionProofError::Status500(ErrorResponse) => {
                GetTransactionProofError::Status500(ErrorResponse)
            }
            RustGetTransactionProofError::Statusdefault() => {
                GetTransactionProofError::Statusdefault()
            }
            RustGetTransactionProofError::DefaultResponse() => {
                GetTransactionProofError::DefaultResponse()
            }
            RustGetTransactionProofError::UnknownValue(value) => {
                GetTransactionProofError::UnknownValue(value.to_string())
            }
        }
    }
}
