/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetParticipationKeyByIdError as RustGetParticipationKeyByIdError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, ParticipationKey};

// Import request body type if needed

/// struct for typed errors of method [`get_participation_key_by_id`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetParticipationKeyByIdError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status404(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetParticipationKeyByIdError> for GetParticipationKeyByIdError {
    fn from(e: RustGetParticipationKeyByIdError) -> Self {
        match e {
            RustGetParticipationKeyByIdError::Status400(v) => {
                GetParticipationKeyByIdError::Status400(v.into())
            }
            RustGetParticipationKeyByIdError::Status401(v) => {
                GetParticipationKeyByIdError::Status401(v.into())
            }
            RustGetParticipationKeyByIdError::Status404(v) => {
                GetParticipationKeyByIdError::Status404(v.into())
            }
            RustGetParticipationKeyByIdError::Status500(v) => {
                GetParticipationKeyByIdError::Status500(v.into())
            }
            RustGetParticipationKeyByIdError::Statusdefault() => {
                GetParticipationKeyByIdError::Statusdefault()
            }
            RustGetParticipationKeyByIdError::DefaultResponse() => {
                GetParticipationKeyByIdError::DefaultResponse()
            }
            RustGetParticipationKeyByIdError::UnknownValue(v) => {
                GetParticipationKeyByIdError::UnknownValue(v.into())
            }
        }
    }
}
