/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetBlockLogsError as RustGetBlockLogsError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, GetBlockLogs};

// Import request body type if needed

/// struct for typed errors of method [`get_block_logs`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetBlockLogsError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status404(ErrorResponse),
    Status500(ErrorResponse),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetBlockLogsError> for GetBlockLogsError {
    fn from(e: RustGetBlockLogsError) -> Self {
        match e {
            RustGetBlockLogsError::Status400(ErrorResponse) => {
                GetBlockLogsError::Status400(ErrorResponse)
            }
            RustGetBlockLogsError::Status401(ErrorResponse) => {
                GetBlockLogsError::Status401(ErrorResponse)
            }
            RustGetBlockLogsError::Status404(ErrorResponse) => {
                GetBlockLogsError::Status404(ErrorResponse)
            }
            RustGetBlockLogsError::Status500(ErrorResponse) => {
                GetBlockLogsError::Status500(ErrorResponse)
            }
            RustGetBlockLogsError::DefaultResponse() => GetBlockLogsError::DefaultResponse(),
            RustGetBlockLogsError::UnknownValue(value) => {
                GetBlockLogsError::UnknownValue(value.to_string())
            }
        }
    }
}
