/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::parameter_enums::*;
use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetPendingTransactionsError as RustGetPendingTransactionsError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, GetPendingTransactions};

// Import request body type if needed

/// struct for typed errors of method [`get_pending_transactions`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetPendingTransactionsError {
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Status503(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetPendingTransactionsError> for GetPendingTransactionsError {
    fn from(e: RustGetPendingTransactionsError) -> Self {
        match e {
            RustGetPendingTransactionsError::Status401(v) => {
                GetPendingTransactionsError::Status401(v.into())
            }
            RustGetPendingTransactionsError::Status500(v) => {
                GetPendingTransactionsError::Status500(v.into())
            }
            RustGetPendingTransactionsError::Status503(v) => {
                GetPendingTransactionsError::Status503(v.into())
            }
            RustGetPendingTransactionsError::Statusdefault() => {
                GetPendingTransactionsError::Statusdefault()
            }
            RustGetPendingTransactionsError::DefaultResponse() => {
                GetPendingTransactionsError::DefaultResponse()
            }
            RustGetPendingTransactionsError::UnknownValue(v) => {
                GetPendingTransactionsError::UnknownValue(v.into())
            }
        }
    }
}
