/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetBlockTxidsError as RustGetBlockTxidsError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, GetBlockTxids};

// Import request body type if needed

/// struct for typed errors of method [`get_block_txids`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetBlockTxidsError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status404(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetBlockTxidsError> for GetBlockTxidsError {
    fn from(e: RustGetBlockTxidsError) -> Self {
        match e {
            RustGetBlockTxidsError::Status400(v) => GetBlockTxidsError::Status400(v.into()),
            RustGetBlockTxidsError::Status401(v) => GetBlockTxidsError::Status401(v.into()),
            RustGetBlockTxidsError::Status404(v) => GetBlockTxidsError::Status404(v.into()),
            RustGetBlockTxidsError::Status500(v) => GetBlockTxidsError::Status500(v.into()),
            RustGetBlockTxidsError::Statusdefault() => GetBlockTxidsError::Statusdefault(),
            RustGetBlockTxidsError::DefaultResponse() => GetBlockTxidsError::DefaultResponse(),
            RustGetBlockTxidsError::UnknownValue(v) => GetBlockTxidsError::UnknownValue(v.into()),
        }
    }
}
