/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetBlockHashError as RustGetBlockHashError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, GetBlockHash};

// Import request body type if needed

/// struct for typed errors of method [`get_block_hash`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetBlockHashError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status404(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetBlockHashError> for GetBlockHashError {
    fn from(e: RustGetBlockHashError) -> Self {
        match e {
            RustGetBlockHashError::Status400(v) => GetBlockHashError::Status400(v.into()),
            RustGetBlockHashError::Status401(v) => GetBlockHashError::Status401(v.into()),
            RustGetBlockHashError::Status404(v) => GetBlockHashError::Status404(v.into()),
            RustGetBlockHashError::Status500(v) => GetBlockHashError::Status500(v.into()),
            RustGetBlockHashError::Statusdefault() => GetBlockHashError::Statusdefault(),
            RustGetBlockHashError::DefaultResponse() => GetBlockHashError::DefaultResponse(),
            RustGetBlockHashError::UnknownValue(v) => GetBlockHashError::UnknownValue(v.into()),
        }
    }
}
