/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetApplicationBoxByNameError as RustGetApplicationBoxByNameError;

// Import all custom types used by this endpoint
use crate::models::{Box, ErrorResponse};

// Import request body type if needed

/// struct for typed errors of method [`get_application_box_by_name`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetApplicationBoxByNameError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status404(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetApplicationBoxByNameError> for GetApplicationBoxByNameError {
    fn from(e: RustGetApplicationBoxByNameError) -> Self {
        match e {
            RustGetApplicationBoxByNameError::Status400(ErrorResponse) => {
                GetApplicationBoxByNameError::Status400(ErrorResponse)
            }
            RustGetApplicationBoxByNameError::Status401(ErrorResponse) => {
                GetApplicationBoxByNameError::Status401(ErrorResponse)
            }
            RustGetApplicationBoxByNameError::Status404(ErrorResponse) => {
                GetApplicationBoxByNameError::Status404(ErrorResponse)
            }
            RustGetApplicationBoxByNameError::Status500(ErrorResponse) => {
                GetApplicationBoxByNameError::Status500(ErrorResponse)
            }
            RustGetApplicationBoxByNameError::Statusdefault() => {
                GetApplicationBoxByNameError::Statusdefault()
            }
            RustGetApplicationBoxByNameError::DefaultResponse() => {
                GetApplicationBoxByNameError::DefaultResponse()
            }
            RustGetApplicationBoxByNameError::UnknownValue(value) => {
                GetApplicationBoxByNameError::UnknownValue(value.to_string())
            }
        }
    }
}
