/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetGenesisError as RustGetGenesisError;

// Import all custom types used by this endpoint
use crate::models::Genesis;

// Import request body type if needed

/// struct for typed errors of method [`get_genesis`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetGenesisError {
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetGenesisError> for GetGenesisError {
    fn from(e: RustGetGenesisError) -> Self {
        match e {
            RustGetGenesisError::Statusdefault() => GetGenesisError::Statusdefault(),
            RustGetGenesisError::DefaultResponse() => GetGenesisError::DefaultResponse(),
            RustGetGenesisError::UnknownValue(value) => {
                GetGenesisError::UnknownValue(value.to_string())
            }
        }
    }
}
