/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::parameter_enums::*;
use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetPendingTransactionsByAddressError as RustGetPendingTransactionsByAddressError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, GetPendingTransactionsByAddress};

// Import request body type if needed

/// struct for typed errors of method [`get_pending_transactions_by_address`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetPendingTransactionsByAddressError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Status503(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<GetPendingTransactionsByAddressError> for RustGetPendingTransactionsByAddressError {
    fn from(e: GetPendingTransactionsByAddressError) -> Self {
        match e {
            GetPendingTransactionsByAddressError::Status400(ErrorResponse) => {
                RustGetPendingTransactionsByAddressError::Status400(ErrorResponse)
            }
            GetPendingTransactionsByAddressError::Status401(ErrorResponse) => {
                RustGetPendingTransactionsByAddressError::Status401(ErrorResponse)
            }
            GetPendingTransactionsByAddressError::Status500(ErrorResponse) => {
                RustGetPendingTransactionsByAddressError::Status500(ErrorResponse)
            }
            GetPendingTransactionsByAddressError::Status503(ErrorResponse) => {
                RustGetPendingTransactionsByAddressError::Status503(ErrorResponse)
            }
            GetPendingTransactionsByAddressError::Statusdefault() => {
                RustGetPendingTransactionsByAddressError::Statusdefault()
            }
            GetPendingTransactionsByAddressError::DefaultResponse() => {
                RustGetPendingTransactionsByAddressError::DefaultResponse()
            }
            GetPendingTransactionsByAddressError::UnknownValue(value) => {
                RustGetPendingTransactionsByAddressError::UnknownValue(value.into())
            }
        }
    }
}

impl From<RustGetPendingTransactionsByAddressError> for GetPendingTransactionsByAddressError {
    fn from(e: RustGetPendingTransactionsByAddressError) -> Self {
        match e {
            RustGetPendingTransactionsByAddressError::Status400(ErrorResponse) => {
                GetPendingTransactionsByAddressError::Status400(ErrorResponse)
            }
            RustGetPendingTransactionsByAddressError::Status401(ErrorResponse) => {
                GetPendingTransactionsByAddressError::Status401(ErrorResponse)
            }
            RustGetPendingTransactionsByAddressError::Status500(ErrorResponse) => {
                GetPendingTransactionsByAddressError::Status500(ErrorResponse)
            }
            RustGetPendingTransactionsByAddressError::Status503(ErrorResponse) => {
                GetPendingTransactionsByAddressError::Status503(ErrorResponse)
            }
            RustGetPendingTransactionsByAddressError::Statusdefault() => {
                GetPendingTransactionsByAddressError::Statusdefault()
            }
            RustGetPendingTransactionsByAddressError::DefaultResponse() => {
                GetPendingTransactionsByAddressError::DefaultResponse()
            }
            RustGetPendingTransactionsByAddressError::UnknownValue(value) => {
                GetPendingTransactionsByAddressError::UnknownValue(value.to_string())
            }
        }
    }
}
