/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetBlockTimeStampOffsetError as RustGetBlockTimeStampOffsetError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, GetBlockTimeStampOffset};

// Import request body type if needed

/// struct for typed errors of method [`get_block_time_stamp_offset`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetBlockTimeStampOffsetError {
    Status400(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetBlockTimeStampOffsetError> for GetBlockTimeStampOffsetError {
    fn from(e: RustGetBlockTimeStampOffsetError) -> Self {
        match e {
            RustGetBlockTimeStampOffsetError::Status400(ErrorResponse) => {
                GetBlockTimeStampOffsetError::Status400(ErrorResponse)
            }
            RustGetBlockTimeStampOffsetError::Statusdefault() => {
                GetBlockTimeStampOffsetError::Statusdefault()
            }
            RustGetBlockTimeStampOffsetError::DefaultResponse() => {
                GetBlockTimeStampOffsetError::DefaultResponse()
            }
            RustGetBlockTimeStampOffsetError::UnknownValue(value) => {
                GetBlockTimeStampOffsetError::UnknownValue(value.to_string())
            }
        }
    }
}
