/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetSyncRoundError as RustGetSyncRoundError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, GetSyncRound};

// Import request body type if needed

/// struct for typed errors of method [`get_sync_round`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetSyncRoundError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Status503(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetSyncRoundError> for GetSyncRoundError {
    fn from(e: RustGetSyncRoundError) -> Self {
        match e {
            RustGetSyncRoundError::Status400(v) => GetSyncRoundError::Status400(v.into()),
            RustGetSyncRoundError::Status401(v) => GetSyncRoundError::Status401(v.into()),
            RustGetSyncRoundError::Status500(v) => GetSyncRoundError::Status500(v.into()),
            RustGetSyncRoundError::Status503(v) => GetSyncRoundError::Status503(v.into()),
            RustGetSyncRoundError::Statusdefault() => GetSyncRoundError::Statusdefault(),
            RustGetSyncRoundError::DefaultResponse() => GetSyncRoundError::DefaultResponse(),
            RustGetSyncRoundError::UnknownValue(v) => GetSyncRoundError::UnknownValue(v.into()),
        }
    }
}
