/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetAssetByIdError as RustGetAssetByIdError;

// Import all custom types used by this endpoint
use crate::models::{Asset, ErrorResponse};

// Import request body type if needed

/// struct for typed errors of method [`get_asset_by_id`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetAssetByIdError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status404(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetAssetByIdError> for GetAssetByIdError {
    fn from(e: RustGetAssetByIdError) -> Self {
        match e {
            RustGetAssetByIdError::Status400(v) => GetAssetByIdError::Status400(v.into()),
            RustGetAssetByIdError::Status401(v) => GetAssetByIdError::Status401(v.into()),
            RustGetAssetByIdError::Status404(v) => GetAssetByIdError::Status404(v.into()),
            RustGetAssetByIdError::Status500(v) => GetAssetByIdError::Status500(v.into()),
            RustGetAssetByIdError::Statusdefault() => GetAssetByIdError::Statusdefault(),
            RustGetAssetByIdError::DefaultResponse() => GetAssetByIdError::DefaultResponse(),
            RustGetAssetByIdError::UnknownValue(v) => GetAssetByIdError::UnknownValue(v.into()),
        }
    }
}
