/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetStatusError as RustGetStatusError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, GetStatus};

// Import request body type if needed

/// struct for typed errors of method [`get_status`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetStatusError {
    Status401(ErrorResponse),
    Status500(String),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetStatusError> for GetStatusError {
    fn from(e: RustGetStatusError) -> Self {
        match e {
            RustGetStatusError::Status401(v) => GetStatusError::Status401(v.into()),
            RustGetStatusError::Status500(v) => GetStatusError::Status500(v),
            RustGetStatusError::Statusdefault() => GetStatusError::Statusdefault(),
            RustGetStatusError::DefaultResponse() => GetStatusError::DefaultResponse(),
            RustGetStatusError::UnknownValue(v) => GetStatusError::UnknownValue(v.into()),
        }
    }
}
