/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetApplicationBoxesError as RustGetApplicationBoxesError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, GetApplicationBoxes};

// Import request body type if needed

/// struct for typed errors of method [`get_application_boxes`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetApplicationBoxesError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetApplicationBoxesError> for GetApplicationBoxesError {
    fn from(e: RustGetApplicationBoxesError) -> Self {
        match e {
            RustGetApplicationBoxesError::Status400(ErrorResponse) => {
                GetApplicationBoxesError::Status400(ErrorResponse)
            }
            RustGetApplicationBoxesError::Status401(ErrorResponse) => {
                GetApplicationBoxesError::Status401(ErrorResponse)
            }
            RustGetApplicationBoxesError::Status500(ErrorResponse) => {
                GetApplicationBoxesError::Status500(ErrorResponse)
            }
            RustGetApplicationBoxesError::Statusdefault() => {
                GetApplicationBoxesError::Statusdefault()
            }
            RustGetApplicationBoxesError::DefaultResponse() => {
                GetApplicationBoxesError::DefaultResponse()
            }
            RustGetApplicationBoxesError::UnknownValue(value) => {
                GetApplicationBoxesError::UnknownValue(value.to_string())
            }
        }
    }
}
