/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::GetLightBlockHeaderProofError as RustGetLightBlockHeaderProofError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, LightBlockHeaderProof};

// Import request body type if needed

/// struct for typed errors of method [`get_light_block_header_proof`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum GetLightBlockHeaderProofError {
    Status401(ErrorResponse),
    Status404(ErrorResponse),
    Status408(ErrorResponse),
    Status500(ErrorResponse),
    Status503(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustGetLightBlockHeaderProofError> for GetLightBlockHeaderProofError {
    fn from(e: RustGetLightBlockHeaderProofError) -> Self {
        match e {
            RustGetLightBlockHeaderProofError::Status401(ErrorResponse) => {
                GetLightBlockHeaderProofError::Status401(ErrorResponse)
            }
            RustGetLightBlockHeaderProofError::Status404(ErrorResponse) => {
                GetLightBlockHeaderProofError::Status404(ErrorResponse)
            }
            RustGetLightBlockHeaderProofError::Status408(ErrorResponse) => {
                GetLightBlockHeaderProofError::Status408(ErrorResponse)
            }
            RustGetLightBlockHeaderProofError::Status500(ErrorResponse) => {
                GetLightBlockHeaderProofError::Status500(ErrorResponse)
            }
            RustGetLightBlockHeaderProofError::Status503(ErrorResponse) => {
                GetLightBlockHeaderProofError::Status503(ErrorResponse)
            }
            RustGetLightBlockHeaderProofError::Statusdefault() => {
                GetLightBlockHeaderProofError::Statusdefault()
            }
            RustGetLightBlockHeaderProofError::DefaultResponse() => {
                GetLightBlockHeaderProofError::DefaultResponse()
            }
            RustGetLightBlockHeaderProofError::UnknownValue(value) => {
                GetLightBlockHeaderProofError::UnknownValue(value.to_string())
            }
        }
    }
}
