/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::parameter_enums::*;
use super::{AlgodApiError, ContentType, Error};

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, PendingTransactionResponse};

// Import request body type if needed

/// struct for typed errors of method [`pending_transaction_information`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum PendingTransactionInformationError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status404(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}
