/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::PutDebugSettingsProfError as RustPutDebugSettingsProfError;

// Import all custom types used by this endpoint
use crate::models::DebugSettingsProf;

// Import request body type if needed

/// struct for typed errors of method [`put_debug_settings_prof`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum PutDebugSettingsProfError {
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustPutDebugSettingsProfError> for PutDebugSettingsProfError {
    fn from(e: RustPutDebugSettingsProfError) -> Self {
        match e {
            RustPutDebugSettingsProfError::DefaultResponse() => {
                PutDebugSettingsProfError::DefaultResponse()
            }
            RustPutDebugSettingsProfError::UnknownValue(value) => {
                PutDebugSettingsProfError::UnknownValue(value.to_string())
            }
        }
    }
}
