/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::RawTransactionError as RustRawTransactionError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, RawTransaction};

// Import request body type if needed

/// struct for typed errors of method [`raw_transaction`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum RawTransactionError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Status503(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustRawTransactionError> for RawTransactionError {
    fn from(e: RustRawTransactionError) -> Self {
        match e {
            RustRawTransactionError::Status400(v) => RawTransactionError::Status400(v.into()),
            RustRawTransactionError::Status401(v) => RawTransactionError::Status401(v.into()),
            RustRawTransactionError::Status500(v) => RawTransactionError::Status500(v.into()),
            RustRawTransactionError::Status503(v) => RawTransactionError::Status503(v.into()),
            RustRawTransactionError::Statusdefault() => RawTransactionError::Statusdefault(),
            RustRawTransactionError::DefaultResponse() => RawTransactionError::DefaultResponse(),
            RustRawTransactionError::UnknownValue(v) => RawTransactionError::UnknownValue(v.into()),
        }
    }
}
