/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::SetSyncRoundError as RustSetSyncRoundError;

// Import all custom types used by this endpoint
use crate::models::ErrorResponse;

// Import request body type if needed

/// struct for typed errors of method [`set_sync_round`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum SetSyncRoundError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Status503(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustSetSyncRoundError> for SetSyncRoundError {
    fn from(e: RustSetSyncRoundError) -> Self {
        match e {
            RustSetSyncRoundError::Status400(v) => SetSyncRoundError::Status400(v.into()),
            RustSetSyncRoundError::Status401(v) => SetSyncRoundError::Status401(v.into()),
            RustSetSyncRoundError::Status500(v) => SetSyncRoundError::Status500(v.into()),
            RustSetSyncRoundError::Status503(v) => SetSyncRoundError::Status503(v.into()),
            RustSetSyncRoundError::Statusdefault() => SetSyncRoundError::Statusdefault(),
            RustSetSyncRoundError::DefaultResponse() => SetSyncRoundError::DefaultResponse(),
            RustSetSyncRoundError::UnknownValue(v) => SetSyncRoundError::UnknownValue(v.into()),
        }
    }
}
