/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::ShutdownNodeError as RustShutdownNodeError;

// Import all custom types used by this endpoint
use crate::models::UnknownJsonValue;

// Import request body type if needed

/// struct for typed errors of method [`shutdown_node`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum ShutdownNodeError {
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustShutdownNodeError> for ShutdownNodeError {
    fn from(e: RustShutdownNodeError) -> Self {
        match e {
            RustShutdownNodeError::DefaultResponse() => ShutdownNodeError::DefaultResponse(),
            RustShutdownNodeError::UnknownValue(v) => ShutdownNodeError::UnknownValue(v.into()),
        }
    }
}
