/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::StartCatchupError as RustStartCatchupError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, StartCatchup};

// Import request body type if needed

/// struct for typed errors of method [`start_catchup`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum StartCatchupError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status408(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<StartCatchupError> for RustStartCatchupError {
    fn from(e: StartCatchupError) -> Self {
        match e {
            StartCatchupError::Status400(ErrorResponse) => {
                RustStartCatchupError::Status400(ErrorResponse)
            }
            StartCatchupError::Status401(ErrorResponse) => {
                RustStartCatchupError::Status401(ErrorResponse)
            }
            StartCatchupError::Status408(ErrorResponse) => {
                RustStartCatchupError::Status408(ErrorResponse)
            }
            StartCatchupError::Status500(ErrorResponse) => {
                RustStartCatchupError::Status500(ErrorResponse)
            }
            StartCatchupError::Statusdefault() => RustStartCatchupError::Statusdefault(),
            StartCatchupError::DefaultResponse() => RustStartCatchupError::DefaultResponse(),
            StartCatchupError::UnknownValue(value) => {
                RustStartCatchupError::UnknownValue(value.into())
            }
        }
    }
}

impl From<RustStartCatchupError> for StartCatchupError {
    fn from(e: RustStartCatchupError) -> Self {
        match e {
            RustStartCatchupError::Status400(ErrorResponse) => {
                StartCatchupError::Status400(ErrorResponse)
            }
            RustStartCatchupError::Status401(ErrorResponse) => {
                StartCatchupError::Status401(ErrorResponse)
            }
            RustStartCatchupError::Status408(ErrorResponse) => {
                StartCatchupError::Status408(ErrorResponse)
            }
            RustStartCatchupError::Status500(ErrorResponse) => {
                StartCatchupError::Status500(ErrorResponse)
            }
            RustStartCatchupError::Statusdefault() => StartCatchupError::Statusdefault(),
            RustStartCatchupError::DefaultResponse() => StartCatchupError::DefaultResponse(),
            RustStartCatchupError::UnknownValue(value) => {
                StartCatchupError::UnknownValue(value.to_string())
            }
        }
    }
}
