/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::StartCatchupError as RustStartCatchupError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, StartCatchup};

// Import request body type if needed

/// struct for typed errors of method [`start_catchup`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum StartCatchupError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status408(ErrorResponse),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustStartCatchupError> for StartCatchupError {
    fn from(e: RustStartCatchupError) -> Self {
        match e {
            RustStartCatchupError::Status400(v) => StartCatchupError::Status400(v.into()),
            RustStartCatchupError::Status401(v) => StartCatchupError::Status401(v.into()),
            RustStartCatchupError::Status408(v) => StartCatchupError::Status408(v.into()),
            RustStartCatchupError::Status500(v) => StartCatchupError::Status500(v.into()),
            RustStartCatchupError::Statusdefault() => StartCatchupError::Statusdefault(),
            RustStartCatchupError::DefaultResponse() => StartCatchupError::DefaultResponse(),
            RustStartCatchupError::UnknownValue(v) => StartCatchupError::UnknownValue(v.into()),
        }
    }
}
