/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::TealDisassembleError as RustTealDisassembleError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, TealDisassemble};

// Import request body type if needed

/// struct for typed errors of method [`teal_disassemble`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum TealDisassembleError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status404(),
    Status500(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustTealDisassembleError> for TealDisassembleError {
    fn from(e: RustTealDisassembleError) -> Self {
        match e {
            RustTealDisassembleError::Status400(ErrorResponse) => {
                TealDisassembleError::Status400(ErrorResponse)
            }
            RustTealDisassembleError::Status401(ErrorResponse) => {
                TealDisassembleError::Status401(ErrorResponse)
            }
            RustTealDisassembleError::Status404() => TealDisassembleError::Status404(),
            RustTealDisassembleError::Status500(ErrorResponse) => {
                TealDisassembleError::Status500(ErrorResponse)
            }
            RustTealDisassembleError::Statusdefault() => TealDisassembleError::Statusdefault(),
            RustTealDisassembleError::DefaultResponse() => TealDisassembleError::DefaultResponse(),
            RustTealDisassembleError::UnknownValue(value) => {
                TealDisassembleError::UnknownValue(value.to_string())
            }
        }
    }
}
