/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::UnsetSyncRoundError as RustUnsetSyncRoundError;

// Import all custom types used by this endpoint
use crate::models::ErrorResponse;

// Import request body type if needed

/// struct for typed errors of method [`unset_sync_round`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum UnsetSyncRoundError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Status503(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustUnsetSyncRoundError> for UnsetSyncRoundError {
    fn from(e: RustUnsetSyncRoundError) -> Self {
        match e {
            RustUnsetSyncRoundError::Status400(v) => UnsetSyncRoundError::Status400(v.into()),
            RustUnsetSyncRoundError::Status401(v) => UnsetSyncRoundError::Status401(v.into()),
            RustUnsetSyncRoundError::Status500(v) => UnsetSyncRoundError::Status500(v.into()),
            RustUnsetSyncRoundError::Status503(v) => UnsetSyncRoundError::Status503(v.into()),
            RustUnsetSyncRoundError::Statusdefault() => UnsetSyncRoundError::Statusdefault(),
            RustUnsetSyncRoundError::DefaultResponse() => UnsetSyncRoundError::DefaultResponse(),
            RustUnsetSyncRoundError::UnknownValue(v) => UnsetSyncRoundError::UnknownValue(v.into()),
        }
    }
}
