/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use algokit_http_client::{HttpClient, HttpMethod};
use std::collections::HashMap;

use super::{AlgodApiError, ContentType, Error};
use algod_client::apis::WaitForBlockError as RustWaitForBlockError;

// Import all custom types used by this endpoint
use crate::models::{ErrorResponse, WaitForBlock};

// Import request body type if needed

/// struct for typed errors of method [`wait_for_block`]
#[derive(Debug, Clone, uniffi::Error)]
pub enum WaitForBlockError {
    Status400(ErrorResponse),
    Status401(ErrorResponse),
    Status500(ErrorResponse),
    Status503(ErrorResponse),
    Statusdefault(),
    DefaultResponse(),
    UnknownValue(crate::models::UnknownJsonValue),
}

impl From<RustWaitForBlockError> for WaitForBlockError {
    fn from(e: RustWaitForBlockError) -> Self {
        match e {
            RustWaitForBlockError::Status400(ErrorResponse) => {
                WaitForBlockError::Status400(ErrorResponse)
            }
            RustWaitForBlockError::Status401(ErrorResponse) => {
                WaitForBlockError::Status401(ErrorResponse)
            }
            RustWaitForBlockError::Status500(ErrorResponse) => {
                WaitForBlockError::Status500(ErrorResponse)
            }
            RustWaitForBlockError::Status503(ErrorResponse) => {
                WaitForBlockError::Status503(ErrorResponse)
            }
            RustWaitForBlockError::Statusdefault() => WaitForBlockError::Statusdefault(),
            RustWaitForBlockError::DefaultResponse() => WaitForBlockError::DefaultResponse(),
            RustWaitForBlockError::UnknownValue(value) => {
                WaitForBlockError::UnknownValue(value.to_string())
            }
        }
    }
}
