[package]
name = "algod_client"
version = "0.0.1"
authors = ["AlgoKit Core Team"]
description = "API client for algod interaction."
license = "MIT"
edition = "2024"

[features]
default = ["default_client"]
default_client = ["algokit_http_client/default_client"]
ffi_uniffi = ["dep:uniffi", "algokit_http_client/ffi_uniffi", "dep:algokit_transact_ffi"]

[dependencies]
# HTTP client
algokit_http_client = { path = "../algokit_http_client", default-features = false, features = ["ffi_uniffi"] }
url = "^2.5"
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
serde_repr = { workspace = true }
serde_bytes = { workspace = true }
serde_path_to_error = { workspace = true }

# Uniffi for FFI bindings
uniffi = { workspace = true, optional = true }
algokit_transact_ffi = { optional = true, version = "0.1.0", path = "../algokit_transact_ffi" }

# AlgoKit dependencies for msgpack and signed transactions
algokit_transact = { path = "../algokit_transact" }
# MessagePack serialization
rmp-serde = { workspace = true }
rmpv = { workspace = true }

# Error handling
snafu = { workspace = true }

# Utilities
base64 = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-test = "^0.4"