/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::MasterDerivationKey;

/// APIV1POSTWalletRequest is the request for `POST /v1/wallet`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct CreateWalletRequest {
    #[serde(
        rename = "master_derivation_key",
        skip_serializing_if = "Option::is_none"
    )]
    pub master_derivation_key: Option<MasterDerivationKey>,
    #[serde(rename = "wallet_driver_name", skip_serializing_if = "Option::is_none")]
    pub wallet_driver_name: Option<String>,
    #[serde(rename = "wallet_name", skip_serializing_if = "Option::is_none")]
    pub wallet_name: Option<String>,
    #[serde(rename = "wallet_password", skip_serializing_if = "Option::is_none")]
    pub wallet_password: Option<String>,
}

impl CreateWalletRequest {
    /// Default constructor for CreateWalletRequest
    pub fn new() -> CreateWalletRequest {
        CreateWalletRequest::default()
    }
}
