/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::Wallet;

/// APIV1GETWalletsResponse is the response to `GET /v1/wallets`
/// friendly:ListWalletsResponse
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct GetWalletsResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<bool>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "wallets", skip_serializing_if = "Option::is_none")]
    pub wallets: Option<Vec<Wallet>>,
}

impl GetWalletsResponse {
    /// Default constructor for GetWalletsResponse
    pub fn new() -> GetWalletsResponse {
        GetWalletsResponse::default()
    }
}
