/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// APIV1GETWalletsRequest is the request for `GET /v1/wallets`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWalletsRequest {}

impl ListWalletsRequest {
    /// Default constructor for ListWalletsRequest
    pub fn new() -> ListWalletsRequest {
        ListWalletsRequest::default()
    }
}
