/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::MultisigSubsig;

/// MultisigSig is the structure that holds multiple Subsigs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct MultisigSig {
    #[serde(rename = "Subsigs", skip_serializing_if = "Option::is_none")]
    pub subsigs: Option<Vec<MultisigSubsig>>,
    #[serde(rename = "Threshold", skip_serializing_if = "Option::is_none")]
    pub threshold: Option<u8>,
    #[serde(rename = "Version", skip_serializing_if = "Option::is_none")]
    pub version: Option<u8>,
}

impl MultisigSig {
    /// Default constructor for MultisigSig
    pub fn new() -> MultisigSig {
        MultisigSig::default()
    }
}
