/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// APIV1POSTWalletReleaseResponse is the response to `POST /v1/wallet/release`
/// friendly:ReleaseWalletHandleTokenResponse
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct PostWalletReleaseResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<bool>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl PostWalletReleaseResponse {
    /// Default constructor for PostWalletReleaseResponse
    pub fn new() -> PostWalletReleaseResponse {
        PostWalletReleaseResponse::default()
    }
}
