/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// APIV1POSTWalletInitResponse is the response to `POST /v1/wallet/init`
/// friendly:InitWalletHandleTokenResponse
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct PostWalletInitResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<bool>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(
        rename = "wallet_handle_token",
        skip_serializing_if = "Option::is_none"
    )]
    pub wallet_handle_token: Option<String>,
}

impl PostWalletInitResponse {
    /// Default constructor for PostWalletInitResponse
    pub fn new() -> PostWalletInitResponse {
        PostWalletInitResponse::default()
    }
}
