/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::PublicKey;

/// APIV1POSTMultisigExportResponse is the response to `POST /v1/multisig/export`
/// friendly:ExportMultisigResponse
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct PostMultisigExportResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<bool>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "multisig_version", skip_serializing_if = "Option::is_none")]
    pub multisig_version: Option<u8>,
    #[serde(rename = "pks", skip_serializing_if = "Option::is_none")]
    pub pks: Option<Vec<PublicKey>>,
    #[serde(rename = "threshold", skip_serializing_if = "Option::is_none")]
    pub threshold: Option<u8>,
}

impl PostMultisigExportResponse {
    /// Default constructor for PostMultisigExportResponse
    pub fn new() -> PostMultisigExportResponse {
        PostMultisigExportResponse::default()
    }
}
