/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_with::{Bytes, serde_as};

/// APIV1POSTMultisigTransactionSignResponse is the response to `POST /v1/multisig/sign`
/// friendly:SignMultisigResponse
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct PostMultisigTransactionSignResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<bool>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "multisig", skip_serializing_if = "Option::is_none")]
    pub multisig: Option<Vec<u8>>,
}

impl PostMultisigTransactionSignResponse {
    /// Default constructor for PostMultisigTransactionSignResponse
    pub fn new() -> PostMultisigTransactionSignResponse {
        PostMultisigTransactionSignResponse::default()
    }
}
