/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_with::{Bytes, serde_as};

/// APIV1POSTKeyExportResponse is the response to `POST /v1/key/export`
/// friendly:ExportKeyResponse
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct PostKeyExportResponse {
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<bool>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "private_key", skip_serializing_if = "Option::is_none")]
    pub private_key: Option<Vec<u8>>,
}

impl PostKeyExportResponse {
    /// Default constructor for PostKeyExportResponse
    pub fn new() -> PostKeyExportResponse {
        PostKeyExportResponse::default()
    }
}
