/*
 * for KMD HTTP API
 *
 * API for KMD (Key Management Daemon)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VersionsRequest is the request for `GET /versions`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct VersionsRequest {}

impl VersionsRequest {
    /// Default constructor for VersionsRequest
    pub fn new() -> VersionsRequest {
        VersionsRequest::default()
    }
}
