/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::AlgorandMsgpack;
use algokit_transact::SignedTransaction as AlgokitSignedTransaction;
use serde::{Deserialize, Serialize};

use crate::models::ApplicationParams;

/// Application index and its parameters
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Application {
    /// [appidx] application index.
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "params")]
    pub params: ApplicationParams,
}

impl AlgorandMsgpack for Application {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl Application {
    /// Constructor for Application
    pub fn new(id: u64, params: ApplicationParams) -> Application {
        Application { id, params }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
