/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use indexmap::IndexMap;

use crate::models;
use std::collections::HashMap;

use crate::models::BlockEvalDelta;

use crate::models::NonAsciiString;

/// BlockStateDelta is a map keyed by state key to BlockEvalDelta.
pub type BlockStateDelta = IndexMap<NonAsciiString, BlockEvalDelta>;
