/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_with::{Bytes, serde_as};

use algokit_transact::AlgorandMsgpack;

/// Tracking metadata for a specific StateProofType.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct BlockStateProofTrackingData {
    /// [v] Vector commitment root of state proof voters (may be absent when not applicable).
    #[serde_as(as = "Option<Bytes>")]
    #[serde(rename = "v", skip_serializing_if = "Option::is_none", default)]
    pub state_proof_voters_commitment: Option<Vec<u8>>,
    /// [t] Online total weight during state proof round.
    #[serde(rename = "t", skip_serializing_if = "Option::is_none", default)]
    pub state_proof_online_total_weight: Option<u64>,
    /// [n] Next round for which state proofs are accepted.
    #[serde(rename = "n", skip_serializing_if = "Option::is_none", default)]
    pub state_proof_next_round: Option<u64>,
}

impl AlgorandMsgpack for BlockStateProofTrackingData {
    const PREFIX: &'static [u8] = b"";
}

impl BlockStateProofTrackingData {
    pub fn new() -> BlockStateProofTrackingData {
        BlockStateProofTrackingData::default()
    }
}
