/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::AlgorandMsgpack;
use serde::{Deserialize, Serialize};
use serde_with::{Bytes, serde_as};

/// Tracking metadata for a specific StateProofType.
#[derive(Clone, Debug, PartialEq)]
#[serde_as]
#[derive(Serialize, Deserialize, Default)]
pub struct BlockStateProofTrackingData {
    /// [v] Vector commitment root of state proof voters (may be absent when not applicable).
    #[serde_as(as = "Option<Bytes>")]
    #[serde(rename = "v", skip_serializing_if = "Option::is_none", default)]
    pub state_proof_voters_commitment: Option<Vec<u8>>,
    /// [t] Online total weight during state proof round.
    #[serde(rename = "t", skip_serializing_if = "Option::is_none", default)]
    pub state_proof_online_total_weight: Option<u64>,
    /// [n] Next round for which state proofs are accepted.
    #[serde(rename = "n", skip_serializing_if = "Option::is_none", default)]
    pub state_proof_next_round: Option<u64>,
}

impl AlgorandMsgpack for BlockStateProofTrackingData {
    const PREFIX: &'static [u8] = b"";
}

impl BlockStateProofTrackingData {
    /// Default constructor for BlockStateProofTrackingData
    pub fn new() -> BlockStateProofTrackingData {
        BlockStateProofTrackingData::default()
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
