/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_with::{Bytes, serde_as};

/// Box name and its content.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Box {
    /// The round for which this information is relevant
    #[serde(rename = "round")]
    pub round: u64,
    /// The box name, base64 encoded
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "name")]
    pub name: Vec<u8>,
    /// The box value, base64 encoded.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "value")]
    pub value: Vec<u8>,
}

impl Box {
    /// Constructor for Box
    pub fn new(round: u64, name: Vec<u8>, value: Vec<u8>) -> Box {
        Box { round, name, value }
    }
}
