/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::{AlgorandMsgpack, SignedTransaction as AlgokitSignedTransaction};
use serde::{Deserialize, Serialize};
use serde_with::{Bytes, serde_as};

/// References a box of an application.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoxReference {
    /// Application ID which this box belongs to
    #[serde(rename = "app")]
    pub app: u64,
    /// Base64 encoded box name
    #[serde_as(as = "Bytes")]
    #[serde(rename = "name")]
    pub name: Vec<u8>,
}

impl AlgorandMsgpack for BoxReference {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl BoxReference {
    /// Constructor for BoxReference
    pub fn new(app: u64, name: Vec<u8>) -> BoxReference {
        BoxReference { app, name }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
