/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::UnknownJsonValue;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenesisAllocation {
    #[serde(rename = "addr")]
    pub addr: String,
    #[serde(rename = "comment")]
    pub comment: String,
    #[serde(rename = "state")]
    pub state: UnknownJsonValue,
}

impl GenesisAllocation {
    /// Constructor for GenesisAllocation
    pub fn new(addr: String, comment: String, state: UnknownJsonValue) -> GenesisAllocation {
        GenesisAllocation {
            addr,
            comment,
            state,
        }
    }
}
