/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Top level transaction IDs in a block.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockTxids {
    /// Block transaction IDs.
    #[serde(rename = "blockTxids")]
    pub block_txids: Vec<String>,
}

impl GetBlockTxids {
    /// Constructor for GetBlockTxids
    pub fn new(block_txids: Vec<String>) -> GetBlockTxids {
        GetBlockTxids { block_txids }
    }
}
