/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Hash of a block header.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockHash {
    /// Block header hash.
    #[serde(rename = "blockHash")]
    pub block_hash: String,
}

impl GetBlockHash {
    /// Constructor for GetBlockHash
    pub fn new(block_hash: String) -> GetBlockHash {
        GetBlockHash { block_hash }
    }
}
