/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

use crate::models::BoxDescriptor;

/// Box names of an application
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetApplicationBoxes {
    #[serde(rename = "boxes")]
    pub boxes: Vec<BoxDescriptor>,
}

impl GetApplicationBoxes {
    /// Constructor for GetApplicationBoxes
    pub fn new(boxes: Vec<BoxDescriptor>) -> GetApplicationBoxes {
        GetApplicationBoxes { boxes }
    }
}
