/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Response containing the timestamp offset in seconds
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockTimeStampOffset {
    /// Timestamp offset in seconds.
    #[serde(rename = "offset")]
    pub offset: u64,
}

impl GetBlockTimeStampOffset {
    /// Constructor for GetBlockTimeStampOffset
    pub fn new(offset: u64) -> GetBlockTimeStampOffset {
        GetBlockTimeStampOffset { offset }
    }
}
