/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::AlgorandMsgpack;
use algokit_transact::SignedTransaction as AlgokitSignedTransaction;
use serde::{Deserialize, Serialize};

/// A transaction group to simulate.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimulateRequestTransactionGroup {
    /// An atomic transaction group.
    #[serde(rename = "txns")]
    pub txns: Vec<AlgokitSignedTransaction>,
}

impl AlgorandMsgpack for SimulateRequestTransactionGroup {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl SimulateRequestTransactionGroup {
    /// Constructor for SimulateRequestTransactionGroup
    pub fn new(txns: Vec<AlgokitSignedTransaction>) -> SimulateRequestTransactionGroup {
        SimulateRequestTransactionGroup { txns }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
