/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::AlgorandMsgpack;
use algokit_transact::SignedTransaction as AlgokitSignedTransaction;
use serde::{Deserialize, Serialize};

use crate::models::EvalDeltaKeyValue;

/// Application state delta.
pub type StateDelta = Vec<EvalDeltaKeyValue>;
