/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact::AlgorandMsgpack;
use algokit_transact::SignedTransaction as AlgokitSignedTransaction;
use serde::{Deserialize, Serialize};

use crate::models::TealValue;

/// Represents a key-value pair in an application store.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TealKeyValue {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: TealValue,
}

impl AlgorandMsgpack for TealKeyValue {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl TealKeyValue {
    /// Constructor for TealKeyValue
    pub fn new(key: String, value: TealValue) -> TealKeyValue {
        TealKeyValue { key, value }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
