/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::AddParticipationKey as RustAddParticipationKey;

/// Participation ID of the submission
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct AddParticipationKey {
    /// encoding of the participation ID.
    pub part_id: String,
}

impl From<RustAddParticipationKey> for AddParticipationKey {
    fn from(rust_struct: RustAddParticipationKey) -> Self {
        Self {
            part_id: rust_struct.part_id.into(),
        }
    }
}

impl From<AddParticipationKey> for RustAddParticipationKey {
    fn from(ffi_struct: AddParticipationKey) -> Self {
        Self {
            part_id: ffi_struct.part_id.into(),
        }
    }
}
