/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::ApplicationParams as RustApplicationParams;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::ApplicationStateSchema;
use crate::models::TealKeyValueStore;

/// Stores the global information associated with an application.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct ApplicationParams {
    /// The address that created this application. This is the address where the parameters and global state for this application can be found.
    pub creator: String,
    /// [approv] approval program.
    pub approval_program: Vec<u8>,
    /// [clearp] approval program.
    pub clear_state_program: Vec<u8>,
    /// [epp] the amount of extra program pages available to this app.
    pub extra_program_pages: Option<u32>,
    pub local_state_schema: Option<ApplicationStateSchema>,
    pub global_state_schema: Option<ApplicationStateSchema>,
    pub global_state: Option<TealKeyValueStore>,
    /// [v] the number of updates to the application programs
    pub version: Option<u64>,
}

impl From<RustApplicationParams> for ApplicationParams {
    fn from(rust_struct: RustApplicationParams) -> Self {
        Self {
            creator: rust_struct.creator,
            approval_program: rust_struct.approval_program,
            clear_state_program: rust_struct.clear_state_program,
            extra_program_pages: rust_struct.extra_program_pages,
            local_state_schema: rust_struct.local_state_schema.map(|v| v.into()),
            global_state_schema: rust_struct.global_state_schema.map(|v| v.into()),
            global_state: rust_struct.global_state.map(|v| v.into()),
            version: rust_struct.version,
        }
    }
}

impl From<ApplicationParams> for RustApplicationParams {
    fn from(ffi_struct: ApplicationParams) -> Self {
        Self {
            creator: ffi_struct.creator,
            approval_program: ffi_struct.approval_program,
            clear_state_program: ffi_struct.clear_state_program,
            extra_program_pages: ffi_struct.extra_program_pages,
            local_state_schema: ffi_struct.local_state_schema.map(|v| v.into()),
            global_state_schema: ffi_struct.global_state_schema.map(|v| v.into()),
            global_state: ffi_struct.global_state.map(|v| v.into()),
            version: ffi_struct.version,
        }
    }
}
