/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::Application as RustApplication;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::ApplicationParams;

/// Application index and its parameters
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct Application {
    /// \[appidx\] application index.
    pub id: u64,
    pub params: ApplicationParams,
}

impl From<RustApplication> for Application {
    fn from(rust_struct: RustApplication) -> Self {
        Self {
            id: rust_struct.id.into(),
            params: rust_struct.params.into(),
        }
    }
}

impl From<Application> for RustApplication {
    fn from(ffi_struct: Application) -> Self {
        Self {
            id: ffi_struct.id.into(),
            params: ffi_struct.params.into(),
        }
    }
}
