/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::AssetHolding as RustAssetHolding;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

/// Describes an asset held by an account.
///
/// Definition:
/// data/basics/userBalance.go : AssetHolding
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct AssetHolding {
    /// \[a\] number of units held.
    pub amount: u64,
    /// Asset ID of the holding.
    pub asset_id: u64,
    /// \[f\] whether or not the holding is frozen.
    pub is_frozen: bool,
}

impl From<RustAssetHolding> for AssetHolding {
    fn from(rust_struct: RustAssetHolding) -> Self {
        Self {
            amount: rust_struct.amount.into(),
            asset_id: rust_struct.asset_id.into(),
            is_frozen: rust_struct.is_frozen.into(),
        }
    }
}

impl From<AssetHolding> for RustAssetHolding {
    fn from(ffi_struct: AssetHolding) -> Self {
        Self {
            amount: ffi_struct.amount.into(),
            asset_id: ffi_struct.asset_id.into(),
            is_frozen: ffi_struct.is_frozen.into(),
        }
    }
}
