/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::AvmKeyValue as RustAvmKeyValue;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::AvmValue;

/// Represents an AVM key-value pair in an application store.
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct AvmKeyValue {
    pub key: Vec<u8>,
    pub value: AvmValue,
}

impl From<RustAvmKeyValue> for AvmKeyValue {
    fn from(rust_struct: RustAvmKeyValue) -> Self {
        Self {
            key: rust_struct.key.into(),
            value: rust_struct.value.into(),
        }
    }
}

impl From<AvmKeyValue> for RustAvmKeyValue {
    fn from(ffi_struct: AvmKeyValue) -> Self {
        Self {
            key: ffi_struct.key.into(),
            value: ffi_struct.value.into(),
        }
    }
}
