/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::AvmValue as RustAvmValue;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

/// Represents an AVM value.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct AvmValue {
    /// value type. Value `1` refers to **bytes**, value `2` refers to **uint64**
    pub r#type: u64,
    /// bytes value.
    pub bytes: Option<String>,
    /// uint value.
    pub uint: Option<u64>,
}

impl From<RustAvmValue> for AvmValue {
    fn from(rust_struct: RustAvmValue) -> Self {
        Self {
            r#type: rust_struct.r#type.into(),
            bytes: rust_struct.bytes.map(|v| v.into()),
            uint: rust_struct.uint.map(|v| v.into()),
        }
    }
}

impl From<AvmValue> for RustAvmValue {
    fn from(ffi_struct: AvmValue) -> Self {
        Self {
            r#type: ffi_struct.r#type.into(),
            bytes: ffi_struct.bytes.map(|v| v.into()),
            uint: ffi_struct.uint.map(|v| v.into()),
        }
    }
}
