/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::BoxDescriptor as RustBoxDescriptor;

/// Box descriptor describes a Box.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct BoxDescriptor {
    /// Base64 encoded box name
    pub name: Vec<u8>,
}

impl From<RustBoxDescriptor> for BoxDescriptor {
    fn from(rust_struct: RustBoxDescriptor) -> Self {
        Self {
            name: rust_struct.name,
        }
    }
}

impl From<BoxDescriptor> for RustBoxDescriptor {
    fn from(ffi_struct: BoxDescriptor) -> Self {
        Self {
            name: ffi_struct.name,
        }
    }
}
