/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::DryrunRequest as RustDryrunRequest;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::Account;
use crate::models::Application;
use crate::models::DryrunSource;

/// Request data type for dryrun endpoint. Given the Transactions and simulated ledger state upload, run TEAL scripts and return debugging information.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct DryrunRequest {
    pub txns: Vec<AlgokitSignedTransaction>,
    pub accounts: Vec<Account>,
    pub apps: Vec<Application>,
    /// ProtocolVersion specifies a specific version string to operate under, otherwise whatever the current protocol of the network this algod is running in.
    pub protocol_version: String,
    /// Round is available to some TEAL scripts. Defaults to the current round on the network this algod is attached to.
    pub round: u64,
    /// LatestTimestamp is available to some TEAL scripts. Defaults to the latest confirmed timestamp this algod is attached to.
    pub latest_timestamp: u64,
    pub sources: Vec<DryrunSource>,
}

impl From<RustDryrunRequest> for DryrunRequest {
    fn from(rust_struct: RustDryrunRequest) -> Self {
        Self {
            txns: rust_struct.txns.into_iter().map(|v| v.into()).collect(),
            accounts: rust_struct.accounts.into_iter().map(|v| v.into()).collect(),
            apps: rust_struct.apps.into_iter().map(|v| v.into()).collect(),
            protocol_version: rust_struct.protocol_version.into(),
            round: rust_struct.round.into(),
            latest_timestamp: rust_struct.latest_timestamp.into(),
            sources: rust_struct.sources.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl From<DryrunRequest> for RustDryrunRequest {
    fn from(ffi_struct: DryrunRequest) -> Self {
        Self {
            txns: ffi_struct.txns.into_iter().map(|v| v.into()).collect(),
            accounts: ffi_struct.accounts.into_iter().map(|v| v.into()).collect(),
            apps: ffi_struct.apps.into_iter().map(|v| v.into()).collect(),
            protocol_version: ffi_struct.protocol_version.into(),
            round: ffi_struct.round.into(),
            latest_timestamp: ffi_struct.latest_timestamp.into(),
            sources: ffi_struct.sources.into_iter().map(|v| v.into()).collect(),
        }
    }
}
