/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::DryrunSource as RustDryrunSource;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

/// DryrunSource is TEAL source text that gets uploaded, compiled, and inserted into transactions or application state.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct DryrunSource {
    /// FieldName is what kind of sources this is. If lsig then it goes into the transactions[this.TxnIndex].LogicSig. If approv or clearp it goes into the Approval Program or Clear State Program of application[this.AppIndex].
    pub field_name: String,
    pub source: String,
    pub txn_index: u64,
    pub app_index: u64,
}

impl From<RustDryrunSource> for DryrunSource {
    fn from(rust_struct: RustDryrunSource) -> Self {
        Self {
            field_name: rust_struct.field_name,
            source: rust_struct.source,
            txn_index: rust_struct.txn_index,
            app_index: rust_struct.app_index,
        }
    }
}

impl From<DryrunSource> for RustDryrunSource {
    fn from(ffi_struct: DryrunSource) -> Self {
        Self {
            field_name: ffi_struct.field_name,
            source: ffi_struct.source,
            txn_index: ffi_struct.txn_index,
            app_index: ffi_struct.app_index,
        }
    }
}
