/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::DryrunState as RustDryrunState;

use crate::models::TealValue;

/// Stores the TEAL eval step data
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct DryrunState {
    /// Line number
    pub line: u64,
    /// Program counter
    pub pc: u64,
    pub stack: Vec<TealValue>,
    pub scratch: Option<Vec<TealValue>>,
    /// Evaluation error if any
    pub error: Option<String>,
}

impl From<RustDryrunState> for DryrunState {
    fn from(rust_struct: RustDryrunState) -> Self {
        Self {
            line: rust_struct.line.into(),
            pc: rust_struct.pc.into(),
            stack: rust_struct.stack.into_iter().map(|v| v.into()).collect(),
            scratch: rust_struct.scratch.map(|v| v.into()),
            error: rust_struct.error.map(|v| v.into()),
        }
    }
}

impl From<DryrunState> for RustDryrunState {
    fn from(ffi_struct: DryrunState) -> Self {
        Self {
            line: ffi_struct.line.into(),
            pc: ffi_struct.pc.into(),
            stack: ffi_struct.stack.into_iter().map(|v| v.into()).collect(),
            scratch: ffi_struct.scratch.map(|v| v.into()),
            error: ffi_struct.error.map(|v| v.into()),
        }
    }
}
