/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::ErrorResponse as RustErrorResponse;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::UnknownJsonValue;

/// An error response with optional data field.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct ErrorResponse {
    pub data: Option<UnknownJsonValue>,
    pub message: String,
}

impl From<RustErrorResponse> for ErrorResponse {
    fn from(rust_struct: RustErrorResponse) -> Self {
        Self {
            data: rust_struct.data.map(|v| v.into()),
            message: rust_struct.message.into(),
        }
    }
}

impl From<ErrorResponse> for RustErrorResponse {
    fn from(ffi_struct: ErrorResponse) -> Self {
        Self {
            data: ffi_struct.data.map(|v| v.into()),
            message: ffi_struct.message.into(),
        }
    }
}
