/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::GenesisAllocation as RustGenesisAllocation;

use crate::models::UnknownJsonValue;

#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct GenesisAllocation {
    pub addr: String,
    pub comment: String,
    pub state: UnknownJsonValue,
}

impl From<RustGenesisAllocation> for GenesisAllocation {
    fn from(rust_struct: RustGenesisAllocation) -> Self {
        Self {
            addr: rust_struct.addr,
            comment: rust_struct.comment,
            state: rust_struct.state.into(),
        }
    }
}

impl From<GenesisAllocation> for RustGenesisAllocation {
    fn from(ffi_struct: GenesisAllocation) -> Self {
        Self {
            addr: ffi_struct.addr,
            comment: ffi_struct.comment,
            state: ffi_struct.state.into(),
        }
    }
}
