/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::Genesis as RustGenesis;

use crate::models::GenesisAllocation;

#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct Genesis {
    pub alloc: Vec<GenesisAllocation>,
    pub comment: Option<String>,
    pub devmode: Option<bool>,
    pub fees: String,
    pub id: String,
    pub network: String,
    pub proto: String,
    pub rwd: String,
    pub timestamp: u64,
}

impl From<RustGenesis> for Genesis {
    fn from(rust_struct: RustGenesis) -> Self {
        Self {
            alloc: rust_struct.alloc.into_iter().map(|v| v.into()).collect(),
            comment: rust_struct.comment,
            devmode: rust_struct.devmode,
            fees: rust_struct.fees,
            id: rust_struct.id,
            network: rust_struct.network,
            proto: rust_struct.proto,
            rwd: rust_struct.rwd,
            timestamp: rust_struct.timestamp,
        }
    }
}

impl From<Genesis> for RustGenesis {
    fn from(ffi_struct: Genesis) -> Self {
        Self {
            alloc: ffi_struct.alloc.into_iter().map(|v| v.into()).collect(),
            comment: ffi_struct.comment,
            devmode: ffi_struct.devmode,
            fees: ffi_struct.fees,
            id: ffi_struct.id,
            network: ffi_struct.network,
            proto: ffi_struct.proto,
            rwd: ffi_struct.rwd,
            timestamp: ffi_struct.timestamp,
        }
    }
}
