/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::GetBlockTxids as RustGetBlockTxids;

/// Top level transaction IDs in a block.
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct GetBlockTxids {
    /// Block transaction IDs.
    pub block_txids: Vec<String>,
}

impl From<RustGetBlockTxids> for GetBlockTxids {
    fn from(rust_struct: RustGetBlockTxids) -> Self {
        Self {
            block_txids: rust_struct
                .block_txids
                .into_iter()
                .map(|v| v.into())
                .collect(),
        }
    }
}

impl From<GetBlockTxids> for RustGetBlockTxids {
    fn from(ffi_struct: GetBlockTxids) -> Self {
        Self {
            block_txids: ffi_struct
                .block_txids
                .into_iter()
                .map(|v| v.into())
                .collect(),
        }
    }
}
