/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::GetPendingTransactionsByAddress as RustGetPendingTransactionsByAddress;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::UnknownJsonValue;

/// PendingTransactions is an array of signed transactions exactly as they were submitted.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct GetPendingTransactionsByAddress {
    /// An array of signed transaction objects.
    pub top_transactions: Vec<AlgokitSignedTransaction>,
    /// Total number of transactions in the pool.
    pub total_transactions: u64,
}

impl From<RustGetPendingTransactionsByAddress> for GetPendingTransactionsByAddress {
    fn from(rust_struct: RustGetPendingTransactionsByAddress) -> Self {
        Self {
            top_transactions: rust_struct
                .top_transactions
                .into_iter()
                .map(|v| v.into())
                .collect(),
            total_transactions: rust_struct.total_transactions,
        }
    }
}
