/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::GetBlockTimeStampOffset as RustGetBlockTimeStampOffset;

/// Response containing the timestamp offset in seconds
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct GetBlockTimeStampOffset {
    /// Timestamp offset in seconds.
    pub offset: u64,
}

impl From<RustGetBlockTimeStampOffset> for GetBlockTimeStampOffset {
    fn from(rust_struct: RustGetBlockTimeStampOffset) -> Self {
        Self {
            offset: rust_struct.offset.into(),
        }
    }
}

impl From<GetBlockTimeStampOffset> for RustGetBlockTimeStampOffset {
    fn from(ffi_struct: GetBlockTimeStampOffset) -> Self {
        Self {
            offset: ffi_struct.offset.into(),
        }
    }
}
