/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::Block;

/// Encoded block object.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct GetBlock {
    /// Block data including header and transactions.
    pub block: Block,
    /// Block certificate (msgpack only).
    pub cert: Option<Vec<u8>>,
}
