/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::GetBlockHash as RustGetBlockHash;

/// Hash of a block header.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct GetBlockHash {
    /// Block header hash.
    pub block_hash: String,
}

impl From<RustGetBlockHash> for GetBlockHash {
    fn from(rust_struct: RustGetBlockHash) -> Self {
        Self {
            block_hash: rust_struct.block_hash,
        }
    }
}

impl From<GetBlockHash> for RustGetBlockHash {
    fn from(ffi_struct: GetBlockHash) -> Self {
        Self {
            block_hash: ffi_struct.block_hash,
        }
    }
}
