/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::GetBlockLogs as RustGetBlockLogs;

use crate::models::AppCallLogs;

/// All logs emitted in the given round. Each app call, whether top-level or inner, that contains logs results in a separate AppCallLogs object. Therefore there may be multiple AppCallLogs with the same application ID and outer transaction ID in the event of multiple inner app calls to the same app. App calls with no logs are not included in the response. AppCallLogs are returned in the same order that their corresponding app call appeared in the block (pre-order traversal of inner app calls)
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct GetBlockLogs {
    pub logs: Vec<AppCallLogs>,
}

impl From<RustGetBlockLogs> for GetBlockLogs {
    fn from(rust_struct: RustGetBlockLogs) -> Self {
        Self {
            logs: rust_struct.logs.into(),
        }
    }
}

impl From<GetBlockLogs> for RustGetBlockLogs {
    fn from(ffi_struct: GetBlockLogs) -> Self {
        Self {
            logs: ffi_struct.logs.into(),
        }
    }
}
