/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::GetBlock as RustGetBlock;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::Block;

/// Encoded block object.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct GetBlock {
    /// Block data including header and transactions.
    pub block: Block,
    /// Block certificate (msgpack only).
    pub cert: Option<Vec<u8>>,
}

impl From<RustGetBlock> for GetBlock {
    fn from(rust_struct: RustGetBlock) -> Self {
        Self {
            block: rust_struct.block.into(),
            cert: rust_struct.cert,
        }
    }
}

impl TryFrom<GetBlock> for RustGetBlock {
    type Error = algokit_transact_ffi::AlgoKitTransactError;

    fn try_from(ffi_struct: GetBlock) -> Result<Self, Self::Error> {
        Ok(Self {
            block: ffi_struct.block.try_into()?,
            cert: ffi_struct.cert,
        })
    }
}
