/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::LedgerStateDeltaForTransactionGroup as RustLedgerStateDeltaForTransactionGroup;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::LedgerStateDelta;

/// Contains a ledger delta for a single transaction group
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct LedgerStateDeltaForTransactionGroup {
    pub delta: LedgerStateDelta,
    pub ids: Vec<String>,
}

impl From<RustLedgerStateDeltaForTransactionGroup> for LedgerStateDeltaForTransactionGroup {
    fn from(rust_struct: RustLedgerStateDeltaForTransactionGroup) -> Self {
        Self {
            delta: rust_struct.delta.into(),
            ids: rust_struct.ids.into(),
        }
    }
}

impl From<LedgerStateDeltaForTransactionGroup> for RustLedgerStateDeltaForTransactionGroup {
    fn from(ffi_struct: LedgerStateDeltaForTransactionGroup) -> Self {
        Self {
            delta: ffi_struct.delta.into(),
            ids: ffi_struct.ids.into(),
        }
    }
}
