/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::ParticipationKey as RustParticipationKey;

use crate::models::AccountParticipation;

/// Represents a participation key used by the node.
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct ParticipationKey {
    /// The key's ParticipationID.
    pub id: String,
    /// Address the key was generated for.
    pub address: String,
    /// When registered, this is the first round it may be used.
    pub effective_first_valid: Option<u64>,
    /// When registered, this is the last round it may be used.
    pub effective_last_valid: Option<u64>,
    /// Round when this key was last used to vote.
    pub last_vote: Option<u64>,
    /// Round when this key was last used to propose a block.
    pub last_block_proposal: Option<u64>,
    /// Round when this key was last used to generate a state proof.
    pub last_state_proof: Option<u64>,
    pub key: AccountParticipation,
}

impl From<RustParticipationKey> for ParticipationKey {
    fn from(rust_struct: RustParticipationKey) -> Self {
        Self {
            id: rust_struct.id.into(),
            address: rust_struct.address.into(),
            effective_first_valid: rust_struct.effective_first_valid.into(),
            effective_last_valid: rust_struct.effective_last_valid.into(),
            last_vote: rust_struct.last_vote.into(),
            last_block_proposal: rust_struct.last_block_proposal.into(),
            last_state_proof: rust_struct.last_state_proof.into(),
            key: rust_struct.key.into(),
        }
    }
}

impl From<ParticipationKey> for RustParticipationKey {
    fn from(ffi_struct: ParticipationKey) -> Self {
        Self {
            id: ffi_struct.id.into(),
            address: ffi_struct.address.into(),
            effective_first_valid: ffi_struct.effective_first_valid.into(),
            effective_last_valid: ffi_struct.effective_last_valid.into(),
            last_vote: ffi_struct.last_vote.into(),
            last_block_proposal: ffi_struct.last_block_proposal.into(),
            last_state_proof: ffi_struct.last_state_proof.into(),
            key: ffi_struct.key.into(),
        }
    }
}
