/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::PendingTransactionResponse as RustPendingTransactionResponse;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::AccountStateDelta;
use crate::models::StateDelta;
use crate::models::UnknownJsonValue;

/// Details about a pending transaction. If the transaction was recently confirmed, includes confirmation details like the round and reward details.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct PendingTransactionResponse {
    /// The asset index if the transaction was found and it created an asset.
    pub asset_id: Option<u64>,
    /// The application index if the transaction was found and it created an application.
    pub app_id: Option<u64>,
    /// Rewards in microalgos applied to the close remainder to account.
    pub close_rewards: Option<u64>,
    /// Closing amount for the transaction.
    pub closing_amount: Option<u64>,
    /// The number of the asset's unit that were transferred to the close-to address.
    pub asset_closing_amount: Option<u64>,
    /// The round where this transaction was confirmed, if present.
    pub confirmed_round: Option<u64>,
    /// Indicates that the transaction was kicked out of this node's transaction pool (and specifies why that happened).  An empty string indicates the transaction wasn't kicked out of this node's txpool due to an error.
    pub pool_error: String,
    /// Rewards in microalgos applied to the receiver account.
    pub receiver_rewards: Option<u64>,
    /// Rewards in microalgos applied to the sender account.
    pub sender_rewards: Option<u64>,
    /// Local state key/value changes for the application being executed by this transaction.
    pub local_state_delta: Option<Vec<AccountStateDelta>>,
    pub global_state_delta: Option<StateDelta>,
    /// Logs for the application being executed by this transaction.
    pub logs: Option<Vec<Vec<u8>>>,
    /// Inner transactions produced by application execution.
    pub inner_txns: Option<Vec<PendingTransactionResponse>>,
    /// The raw signed transaction.
    pub txn: AlgokitSignedTransaction,
}

impl From<RustPendingTransactionResponse> for PendingTransactionResponse {
    fn from(rust_struct: RustPendingTransactionResponse) -> Self {
        Self {
            asset_id: rust_struct.asset_id.into(),
            app_id: rust_struct.app_id.into(),
            close_rewards: rust_struct.close_rewards.into(),
            closing_amount: rust_struct.closing_amount.into(),
            asset_closing_amount: rust_struct.asset_closing_amount.into(),
            confirmed_round: rust_struct.confirmed_round.into(),
            pool_error: rust_struct.pool_error.into(),
            receiver_rewards: rust_struct.receiver_rewards.into(),
            sender_rewards: rust_struct.sender_rewards.into(),
            local_state_delta: rust_struct.local_state_delta.into(),
            global_state_delta: rust_struct.global_state_delta.into(),
            logs: rust_struct.logs.into(),
            inner_txns: rust_struct.inner_txns.into(),
            txn: rust_struct.txn.into(),
        }
    }
}

impl From<PendingTransactionResponse> for RustPendingTransactionResponse {
    fn from(ffi_struct: PendingTransactionResponse) -> Self {
        Self {
            asset_id: ffi_struct.asset_id.into(),
            app_id: ffi_struct.app_id.into(),
            close_rewards: ffi_struct.close_rewards.into(),
            closing_amount: ffi_struct.closing_amount.into(),
            asset_closing_amount: ffi_struct.asset_closing_amount.into(),
            confirmed_round: ffi_struct.confirmed_round.into(),
            pool_error: ffi_struct.pool_error.into(),
            receiver_rewards: ffi_struct.receiver_rewards.into(),
            sender_rewards: ffi_struct.sender_rewards.into(),
            local_state_delta: ffi_struct.local_state_delta.into(),
            global_state_delta: ffi_struct.global_state_delta.into(),
            logs: ffi_struct.logs.into(),
            inner_txns: ffi_struct.inner_txns.into(),
            txn: ffi_struct.txn.into(),
        }
    }
}
