/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::RawTransaction as RustRawTransaction;

/// Transaction ID of the submission.
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct RawTransaction {
    /// encoding of the transaction hash.
    pub tx_id: String,
}

impl From<RustRawTransaction> for RawTransaction {
    fn from(rust_struct: RustRawTransaction) -> Self {
        Self {
            tx_id: rust_struct.tx_id.into(),
        }
    }
}

impl From<RawTransaction> for RustRawTransaction {
    fn from(ffi_struct: RawTransaction) -> Self {
        Self {
            tx_id: ffi_struct.tx_id.into(),
        }
    }
}
