/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::SignedTxnInBlock as RustSignedTxnInBlock;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::BlockAppEvalDelta;

/// SignedTxnInBlock is a SignedTransaction with additional ApplyData and block-specific metadata.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct SignedTxnInBlock {
    /// SignedTransaction fields (flattened from algokit_transact)
    pub signed_transaction: AlgokitSignedTransaction,
    /// [lsig] Logic signature (program signature).
    pub logic_signature: Option<Vec<u8>>,
    /// [ca] Rewards applied to close-remainder-to account.
    pub closing_amount: Option<u64>,
    /// [aca] Asset closing amount.
    pub asset_closing_amount: Option<u64>,
    /// [rs] Sender rewards.
    pub sender_rewards: Option<u64>,
    /// [rr] Receiver rewards.
    pub receiver_rewards: Option<u64>,
    /// [rc] Close rewards.
    pub close_rewards: Option<u64>,
    /// [dt] State changes from app execution.
    pub eval_delta: Option<BlockAppEvalDelta>,
    /// [caid] Asset ID if created.
    pub config_asset: Option<u64>,
    /// [apid] App ID if created.
    pub application_id: Option<u64>,
    /// [hgi] Has genesis ID flag.
    pub has_genesis_id: Option<bool>,
    /// [hgh] Has genesis hash flag.
    pub has_genesis_hash: Option<bool>,
}

impl From<RustSignedTxnInBlock> for SignedTxnInBlock {
    fn from(rust_struct: RustSignedTxnInBlock) -> Self {
        Self {
            signed_transaction: rust_struct.signed_transaction.into(),
            logic_signature: rust_struct.logic_signature,
            closing_amount: rust_struct.closing_amount,
            asset_closing_amount: rust_struct.asset_closing_amount,
            sender_rewards: rust_struct.sender_rewards,
            receiver_rewards: rust_struct.receiver_rewards,
            close_rewards: rust_struct.close_rewards,
            eval_delta: rust_struct.eval_delta.map(|v| v.into()),
            config_asset: rust_struct.config_asset,
            application_id: rust_struct.application_id,
            has_genesis_id: rust_struct.has_genesis_id,
            has_genesis_hash: rust_struct.has_genesis_hash,
        }
    }
}

impl TryFrom<SignedTxnInBlock> for RustSignedTxnInBlock {
    type Error = algokit_transact_ffi::AlgoKitTransactError;

    fn try_from(ffi_struct: SignedTxnInBlock) -> Result<Self, Self::Error> {
        Ok(Self {
            signed_transaction: ffi_struct.signed_transaction.try_into()?,
            logic_signature: ffi_struct.logic_signature,
            closing_amount: ffi_struct.closing_amount,
            asset_closing_amount: ffi_struct.asset_closing_amount,
            sender_rewards: ffi_struct.sender_rewards,
            receiver_rewards: ffi_struct.receiver_rewards,
            close_rewards: ffi_struct.close_rewards,
            eval_delta: ffi_struct.eval_delta.map(|v| v.try_into()).transpose()?,
            config_asset: ffi_struct.config_asset,
            application_id: ffi_struct.application_id,
            has_genesis_id: ffi_struct.has_genesis_id,
            has_genesis_hash: ffi_struct.has_genesis_hash,
        })
    }
}
