/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::SimulateRequest as RustSimulateRequest;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::SimulateRequestTransactionGroup;
use crate::models::SimulateTraceConfig;

/// Request type for simulation endpoint.
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct SimulateRequest {
    /// The transaction groups to simulate.
    pub txn_groups: Vec<SimulateRequestTransactionGroup>,
    /// If provided, specifies the round preceding the simulation. State changes through this round will be used to run this simulation. Usually only the 4 most recent rounds will be available (controlled by the node config value MaxAcctLookback). If not specified, defaults to the latest available round.
    pub round: Option<u64>,
    /// Allows transactions without signatures to be simulated as if they had correct signatures.
    pub allow_empty_signatures: Option<bool>,
    /// Lifts limits on log opcode usage during simulation.
    pub allow_more_logging: Option<bool>,
    /// Allows access to unnamed resources during simulation.
    pub allow_unnamed_resources: Option<bool>,
    /// Applies extra opcode budget during simulation for each transaction group.
    pub extra_opcode_budget: Option<u64>,
    pub exec_trace_config: Option<SimulateTraceConfig>,
    /// If true, signers for transactions that are missing signatures will be fixed during evaluation.
    pub fix_signers: Option<bool>,
}

impl From<RustSimulateRequest> for SimulateRequest {
    fn from(rust_struct: RustSimulateRequest) -> Self {
        Self {
            txn_groups: rust_struct
                .txn_groups
                .into_iter()
                .map(|v| v.into())
                .collect(),
            round: rust_struct.round.map(|v| v.into()),
            allow_empty_signatures: rust_struct.allow_empty_signatures.map(|v| v.into()),
            allow_more_logging: rust_struct.allow_more_logging.map(|v| v.into()),
            allow_unnamed_resources: rust_struct.allow_unnamed_resources.map(|v| v.into()),
            extra_opcode_budget: rust_struct.extra_opcode_budget.map(|v| v.into()),
            exec_trace_config: rust_struct.exec_trace_config.map(|v| v.into()),
            fix_signers: rust_struct.fix_signers.map(|v| v.into()),
        }
    }
}

impl From<SimulateRequest> for RustSimulateRequest {
    fn from(ffi_struct: SimulateRequest) -> Self {
        Self {
            txn_groups: ffi_struct
                .txn_groups
                .into_iter()
                .map(|v| v.into())
                .collect(),
            round: ffi_struct.round.map(|v| v.into()),
            allow_empty_signatures: ffi_struct.allow_empty_signatures.map(|v| v.into()),
            allow_more_logging: ffi_struct.allow_more_logging.map(|v| v.into()),
            allow_unnamed_resources: ffi_struct.allow_unnamed_resources.map(|v| v.into()),
            extra_opcode_budget: ffi_struct.extra_opcode_budget.map(|v| v.into()),
            exec_trace_config: ffi_struct.exec_trace_config.map(|v| v.into()),
            fix_signers: ffi_struct.fix_signers.map(|v| v.into()),
        }
    }
}
