/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::SimulateTraceConfig as RustSimulateTraceConfig;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

/// An object that configures simulation execution trace.
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct SimulateTraceConfig {
    /// A boolean option for opting in execution trace features simulation endpoint.
    pub enable: Option<bool>,
    /// A boolean option enabling returning stack changes together with execution trace during simulation.
    pub stack_change: Option<bool>,
    /// A boolean option enabling returning scratch slot changes together with execution trace during simulation.
    pub scratch_change: Option<bool>,
    /// A boolean option enabling returning application state changes (global, local, and box changes) with the execution trace during simulation.
    pub state_change: Option<bool>,
}

impl From<RustSimulateTraceConfig> for SimulateTraceConfig {
    fn from(rust_struct: RustSimulateTraceConfig) -> Self {
        Self {
            enable: rust_struct.enable.map(|v| v.into()),
            stack_change: rust_struct.stack_change.map(|v| v.into()),
            scratch_change: rust_struct.scratch_change.map(|v| v.into()),
            state_change: rust_struct.state_change.map(|v| v.into()),
        }
    }
}

impl From<SimulateTraceConfig> for RustSimulateTraceConfig {
    fn from(ffi_struct: SimulateTraceConfig) -> Self {
        Self {
            enable: ffi_struct.enable.map(|v| v.into()),
            stack_change: ffi_struct.stack_change.map(|v| v.into()),
            scratch_change: ffi_struct.scratch_change.map(|v| v.into()),
            state_change: ffi_struct.state_change.map(|v| v.into()),
        }
    }
}
