/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::SimulateRequestTransactionGroup as RustSimulateRequestTransactionGroup;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

/// A transaction group to simulate.
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct SimulateRequestTransactionGroup {
    /// An atomic transaction group.
    pub txns: Vec<AlgokitSignedTransaction>,
}

impl From<RustSimulateRequestTransactionGroup> for SimulateRequestTransactionGroup {
    fn from(rust_struct: RustSimulateRequestTransactionGroup) -> Self {
        Self {
            txns: rust_struct.txns.into_iter().map(|v| v.into()).collect(),
        }
    }
}

impl TryFrom<SimulateRequestTransactionGroup> for RustSimulateRequestTransactionGroup {
    type Error = crate::apis::Error;

    fn try_from(ffi_struct: SimulateRequestTransactionGroup) -> Result<Self, Self::Error> {
        Ok(Self {
            txns: ffi_struct
                .txns
                .into_iter()
                .map(|v| {
                    v.try_into()
                        .map_err(|e: algokit_transact_ffi::AlgoKitTransactError| {
                            crate::apis::Error::Serde {
                                message: e.to_string(),
                            }
                        })
                })
                .collect::<Result<_, _>>()?,
        })
    }
}
