/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::SimulateInitialStates as RustSimulateInitialStates;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::ApplicationInitialStates;

/// Initial states of resources that were accessed during simulation.
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct SimulateInitialStates {
    /// The initial states of accessed application before simulation. The order of this array is arbitrary.
    pub app_initial_states: Option<Vec<ApplicationInitialStates>>,
}

impl From<RustSimulateInitialStates> for SimulateInitialStates {
    fn from(rust_struct: RustSimulateInitialStates) -> Self {
        Self {
            app_initial_states: rust_struct.app_initial_states.into(),
        }
    }
}

impl From<SimulateInitialStates> for RustSimulateInitialStates {
    fn from(ffi_struct: SimulateInitialStates) -> Self {
        Self {
            app_initial_states: ffi_struct.app_initial_states.into(),
        }
    }
}
