/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::StateProofMessage as RustStateProofMessage;

/// Represents the message that the state proofs are attesting to.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct StateProofMessage {
    /// The vector commitment root on all light block headers within a state proof interval.
    pub block_headers_commitment: Vec<u8>,
    /// The vector commitment root of the top N accounts to sign the next StateProof.
    pub voters_commitment: Vec<u8>,
    /// An integer value representing the natural log of the proven weight with 16 bits of precision. This value would be used to verify the next state proof.
    pub ln_proven_weight: u64,
    /// The first round the message attests to.
    pub first_attested_round: u64,
    /// The last round the message attests to.
    pub last_attested_round: u64,
}

impl From<RustStateProofMessage> for StateProofMessage {
    fn from(rust_struct: RustStateProofMessage) -> Self {
        Self {
            block_headers_commitment: rust_struct.block_headers_commitment,
            voters_commitment: rust_struct.voters_commitment,
            ln_proven_weight: rust_struct.ln_proven_weight,
            first_attested_round: rust_struct.first_attested_round,
            last_attested_round: rust_struct.last_attested_round,
        }
    }
}

impl From<StateProofMessage> for RustStateProofMessage {
    fn from(ffi_struct: StateProofMessage) -> Self {
        Self {
            block_headers_commitment: ffi_struct.block_headers_commitment,
            voters_commitment: ffi_struct.voters_commitment,
            ln_proven_weight: ffi_struct.ln_proven_weight,
            first_attested_round: ffi_struct.first_attested_round,
            last_attested_round: ffi_struct.last_attested_round,
        }
    }
}
