/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::StateProof as RustStateProof;

use crate::models::StateProofMessage;

/// Represents a state proof and its corresponding message
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct StateProof {
    pub message: StateProofMessage,
    /// The encoded StateProof for the message.
    pub state_proof: Vec<u8>,
}

impl From<RustStateProof> for StateProof {
    fn from(rust_struct: RustStateProof) -> Self {
        Self {
            message: rust_struct.message.into(),
            state_proof: rust_struct.state_proof.into(),
        }
    }
}

impl From<StateProof> for RustStateProof {
    fn from(ffi_struct: StateProof) -> Self {
        Self {
            message: ffi_struct.message.into(),
            state_proof: ffi_struct.state_proof.into(),
        }
    }
}
