/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::TealKeyValueStore as RustTealKeyValueStore;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::TealKeyValue;

/// Represents a key-value store for use in an application.
#[derive(Clone, Debug, PartialEq)]
pub struct TealKeyValueStore(Vec<TealKeyValue>);

uniffi::custom_newtype!(TealKeyValueStore, Vec<TealKeyValue>);

impl From<RustTealKeyValueStore> for TealKeyValueStore {
    fn from(rust_struct: RustTealKeyValueStore) -> Self {
        Self(rust_struct.into_iter().map(|v| v.into()).collect())
    }
}

impl From<TealKeyValueStore> for RustTealKeyValueStore {
    fn from(ffi_struct: TealKeyValueStore) -> Self {
        ffi_struct.0.into_iter().map(|v| v.into()).collect()
    }
}
