/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::TealDryrun as RustTealDryrun;

use crate::models::DryrunTxnResult;

/// DryrunResponse contains per-txn debug information from a dryrun.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct TealDryrun {
    pub txns: Vec<DryrunTxnResult>,
    pub error: String,
    /// Protocol version is the protocol version Dryrun was operated under.
    pub protocol_version: String,
}

impl From<RustTealDryrun> for TealDryrun {
    fn from(rust_struct: RustTealDryrun) -> Self {
        Self {
            txns: rust_struct.txns.into_iter().map(|v| v.into()).collect(),
            error: rust_struct.error.into(),
            protocol_version: rust_struct.protocol_version.into(),
        }
    }
}
