/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::TealCompile as RustTealCompile;

use crate::models::UnknownJsonValue;

/// Teal compile Result
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct TealCompile {
    /// base32 SHA512_256 of program bytes (Address style)
    pub hash: String,
    /// base64 encoded program bytes
    pub result: Vec<u8>,
    /// JSON of the source map
    pub sourcemap: Option<UnknownJsonValue>,
}

impl From<RustTealCompile> for TealCompile {
    fn from(rust_struct: RustTealCompile) -> Self {
        Self {
            hash: rust_struct.hash.into(),
            result: rust_struct.result.into(),
            sourcemap: rust_struct.sourcemap.map(|v| v.into()),
        }
    }
}

impl From<TealCompile> for RustTealCompile {
    fn from(ffi_struct: TealCompile) -> Self {
        Self {
            hash: ffi_struct.hash.into(),
            result: ffi_struct.result.into(),
            sourcemap: ffi_struct.sourcemap.map(|v| v.into()),
        }
    }
}
