/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::TealKeyValue as RustTealKeyValue;
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use crate::models::TealValue;

/// Represents a key-value pair in an application store.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct TealKeyValue {
    pub key: String,
    pub value: TealValue,
}

impl From<RustTealKeyValue> for TealKeyValue {
    fn from(rust_struct: RustTealKeyValue) -> Self {
        Self {
            key: rust_struct.key.into(),
            value: rust_struct.value.into(),
        }
    }
}

impl From<TealKeyValue> for RustTealKeyValue {
    fn from(ffi_struct: TealKeyValue) -> Self {
        Self {
            key: ffi_struct.key.into(),
            value: ffi_struct.value.into(),
        }
    }
}
