/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::TransactionProof as RustTransactionProof;

/// Proof of transaction in a block.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct TransactionProof {
    /// Proof of transaction membership.
    pub proof: Vec<u8>,
    /// Hash of SignedTxnInBlock for verifying proof.
    pub stibhash: Vec<u8>,
    /// Represents the depth of the tree that is being proven, i.e. the number of edges from a leaf to the root.
    pub treedepth: u64,
    /// Index of the transaction in the block's payset.
    pub idx: u64,
    /// The type of hash function used to create the proof, must be one of:
    ///   * sha512_256
    ///   * sha256
    pub hashtype: String,
}

impl From<RustTransactionProof> for TransactionProof {
    fn from(rust_struct: RustTransactionProof) -> Self {
        Self {
            proof: rust_struct.proof,
            stibhash: rust_struct.stibhash,
            treedepth: rust_struct.treedepth,
            idx: rust_struct.idx,
            hashtype: rust_struct.hashtype,
        }
    }
}

impl From<TransactionProof> for RustTransactionProof {
    fn from(ffi_struct: TransactionProof) -> Self {
        Self {
            proof: ffi_struct.proof,
            stibhash: ffi_struct.stibhash,
            treedepth: ffi_struct.treedepth,
            idx: ffi_struct.idx,
            hashtype: ffi_struct.hashtype,
        }
    }
}
