/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::TransactionParams as RustTransactionParams;

/// TransactionParams contains the parameters that help a client construct
/// a new transaction.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct TransactionParams {
    /// ConsensusVersion indicates the consensus protocol version
    /// as of LastRound.
    pub consensus_version: String,
    /// Fee is the suggested transaction fee
    /// Fee is in units of micro-Algos per byte.
    /// Fee may fall to zero but transactions must still have a fee of
    /// at least MinTxnFee for the current network protocol.
    pub fee: u64,
    /// GenesisHash is the hash of the genesis block.
    pub genesis_hash: Vec<u8>,
    /// GenesisID is an ID listed in the genesis block.
    pub genesis_id: String,
    /// LastRound indicates the last round seen
    pub last_round: u64,
    /// The minimum transaction fee (not per byte) required for the
    /// txn to validate for the current network protocol.
    pub min_fee: u64,
}

impl From<RustTransactionParams> for TransactionParams {
    fn from(rust_struct: RustTransactionParams) -> Self {
        Self {
            consensus_version: rust_struct.consensus_version,
            fee: rust_struct.fee,
            genesis_hash: rust_struct.genesis_hash,
            genesis_id: rust_struct.genesis_id,
            last_round: rust_struct.last_round,
            min_fee: rust_struct.min_fee,
        }
    }
}

impl From<TransactionParams> for RustTransactionParams {
    fn from(ffi_struct: TransactionParams) -> Self {
        Self {
            consensus_version: ffi_struct.consensus_version,
            fee: ffi_struct.fee,
            genesis_hash: ffi_struct.genesis_hash,
            genesis_id: ffi_struct.genesis_id,
            last_round: ffi_struct.last_round,
            min_fee: ffi_struct.min_fee,
        }
    }
}
