/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
use algod_client::models::Version as RustVersion;

use crate::models::BuildVersion;

/// algod version information.
#[derive(Clone, Default, Debug, PartialEq, uniffi::Record)]
pub struct Version {
    pub build: BuildVersion,
    pub genesis_hash_b64: Vec<u8>,
    pub genesis_id: String,
    pub versions: Vec<String>,
}

impl From<RustVersion> for Version {
    fn from(rust_struct: RustVersion) -> Self {
        Self {
            build: rust_struct.build.into(),
            genesis_hash_b64: rust_struct.genesis_hash_b64.into(),
            genesis_id: rust_struct.genesis_id.into(),
            versions: rust_struct.versions.into(),
        }
    }
}

impl From<Version> for RustVersion {
    fn from(ffi_struct: Version) -> Self {
        Self {
            build: ffi_struct.build.into(),
            genesis_hash_b64: ffi_struct.genesis_hash_b64.into(),
            genesis_id: ffi_struct.genesis_id.into(),
            versions: ffi_struct.versions.into(),
        }
    }
}
