/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: Rust OpenAPI Generator
 */

use crate::models;
#[cfg(not(feature = "ffi_uniffi"))]
use algokit_transact::SignedTransaction as AlgokitSignedTransaction;
use serde::{Deserialize, Serialize};

#[cfg(feature = "ffi_uniffi")]
use algokit_transact_ffi::SignedTransaction as AlgokitSignedTransaction;

use algokit_transact::AlgorandMsgpack;

use crate::models::Block;

/// Encoded block object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "ffi_uniffi", derive(uniffi::Record))]
pub struct GetBlock {
    /// Block data including header and transactions.
    #[serde(rename = "block")]
    pub block: Block,
    /// Block certificate (msgpack only).
    #[serde(
        with = "crate::msgpack_value_bytes",
        default,
        rename = "cert",
        skip_serializing_if = "Option::is_none"
    )]
    pub cert: Option<Vec<u8>>,
}

impl AlgorandMsgpack for GetBlock {
    const PREFIX: &'static [u8] = b""; // Adjust prefix as needed for your specific type
}

impl GetBlock {
    /// Constructor for GetBlock
    pub fn new(block: Block) -> GetBlock {
        GetBlock { block, cert: None }
    }

    /// Encode this struct to msgpack bytes using AlgorandMsgpack trait
    pub fn to_msgpack(&self) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        Ok(self.encode()?)
    }

    /// Decode msgpack bytes to this struct using AlgorandMsgpack trait
    pub fn from_msgpack(bytes: &[u8]) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(Self::decode(bytes)?)
    }
}
